apiVersion: xl-release/v1
kind: Templates
spec:
- name: wyndham
  type: xlrelease.Folder
  children:
  - name: wyndham-destroy
    type: xlrelease.Release
    description: |
      This XL Release template shows how to undeploy an application, based on microservices architecture, to AWS EKS using XL Deploy.
    tags:
    - AWS
    - EKS
    - wyndham
    scriptUsername: !value XL_RELEASE_USERNAME
    scriptUserPassword: !value XL_RELEASE_PASSWORD
    phases:
    - name: Undeploy Application
      type: xlrelease.Phase
      tasks:
      - name: Undeploy stateless services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy registry svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-registry
        - name: Undeploy invoice svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-invoice
        - name: Undeploy notification svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-notification
        - name: Undeploy store svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-store
      - name: Undeploy stateful services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy invoice mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-invoice-mysql
        - name: Undeploy store mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-store-mysql
        - name: Undeploy notification mongodb svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-notification-mongodb
      
      # Un-provision namespace
      - name: Undeploy xl-demo namespace
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/wyndham/aws-eks-wyndham/wyndham-namespace
      
    
    # De-provision Infra
    - name: Deprovision Infrastructure
      color: '#ff9e3b'
      type: xlrelease.Phase
      tasks:
      - name: Deprovision AWS EKS cluster
        type: xlrelease.SequentialGroup
        tasks:
        - name: Deprovision EKS config map for workers
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/wyndham-master-EKSCluster-kube-system/wyndham-k8s-configmap
        - name: Update workers dictionary for kube-system environment
          type: xld.UpdateCIProperty
          server: XL Deploy
          ciID: Environments/wyndham/wyndham-master-EKSCluster-kube-system
          ciProperty: dictionaries
          propertyValue: '[]'
        - name: Deprovision EKS workers nodes
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-cloudformation-eks-workers
        - name: Deprovision EKS master node
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-cloudformation-eks-master
      - name: Delete artifacts from S3
        type: xlrelease.SequentialGroup
        tasks:
        - name: Delete artifacts from S3
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-lambda-artifacts
        - name: Delete S3 bucket
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-lambda-bucket
      - name: Deprovision AWS VPC and IAM resources
        type: xlrelease.SequentialGroup
        tasks:
        - name: Deprovision AWS IAM resources
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-cloudformation-eks-user
        - name: Deprovision AWS VPC
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/wyndham/aws-cloudformation-wyndham/wyndham-cloudformation-eks-vpc